Alicanto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bus_signals.urls")),
    path('api/', include("link_apis.urls")),
    path('', include("users.urls")),
    path('', include("reports.urls")),
    path('', include('programacion_bus.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

bus_signals/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
  path("login", views.login_page, name="login"),
  path("no-access", views.no_access, name="no-access"),
  path("", views.dashboard, name="dashboard"),
  path("logout_user/", views.logout_user, name="logout_user"),
  path("bus_list/", views.bus_list, name="bus_list"),
  path("bus_list_view/", views.bus_list_view, name="bus_list_view"),
  path("dic_fusi/", views.dic_fusi, name="dic_fusi"),
  path("bus_detail/<str:pk>/", views.bus_detail, name="bus_detail"),
  path("create_bus/", views.create_bus, name="create_bus"),
  path("create_fusi/", views.create_fusi, name="create_fusi"),
  path("update_bus/<str:pk>/", views.update_bus, name="update_bus"),
  path('update-fusi-code/<str:pk>/', views.update_fusicode, name='update-fusi-code'),
  path("update_fusi/<str:pk>/", views.update_fusi, name="update_fusi"),
  path("delete_bus/<str:pk>/", views.delete_bus, name="delete_bus"),
  path("reports_page/", views.reports_page, name="reports_page"),
  path('energy_record/', views.energy_record, name='energy-record'),
  path("warnings/", views.warnings, name="warnings"),
  path("fusi_dashboard/", views.fusi_dashboard, name="fusi_dashboard"),
 

]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profiles', views.profile, name='profile'),
    path('work_order/', views.create_work_order, name='work_order_form'),
    path('update_ot/<str:pk>/', views.update_ot, name='update_ot'),
    

]

bus_signals/models.py
from django.db import models
import uuid
from datetime import datetime, timedelta
from django.utils import timezone


series_choices = (
    ('Queltehue', 'Queltehue'),
    ('Queltehue-Q2', 'Queltehue-Q2'),
    ('Tricahue', 'Tricahue'),
    ('Retrofit', 'Retrofit'),
    ('Prueba', 'Prueba'),
)
job_choices = (
    ('Electro Mecanico', 'Electro Mecanico'),
    ('Electrico', 'Electrico'),
    ('Electronico', 'Electronico'),
)

message_class_choices = (
    ('Q1', 'Q1'),
    ('Q2', 'Q2'),
)
fusi_code_options = (
  ('Abierto', 'Abierto'),
  ('Cerrado', 'Cerrado'),
)



class Bus(models.Model):
    bus_name = models.CharField('Name', max_length=40, unique=True, blank=False, null=False, db_index=True)
    sniffer = models.CharField('Sniffer', max_length=10, unique=True, blank=False, null=False, db_index=True)
    plate_number = models.CharField('Plate Number', max_length=10, unique=False, blank=True, null=True, db_index=True)
    bus_series = models.CharField('Serie', max_length=100, choices=series_choices, blank=False, null=False, db_index=True)
    client = models.CharField('Client', max_length=20, blank=False, null=False, default='Link', db_index=True)
    lts_soc = models.IntegerField('LTS SOC', default=None, blank=True, null=True, db_index=True)
    lts_odometer = models.IntegerField('LTS Odometer', default=0, blank=True, null=True, db_index=True)
    lts_isolation = models.IntegerField('LTS Isolation', default=0, blank=True, null=True, db_index=True)
    lts_24_volt = models.FloatField('LTS 24 Volt', default=0, blank=True, null=True, db_index=True)
    lts_fusi = models.IntegerField(blank=True, null=True, db_index=True)
    lts_charge = models.IntegerField(blank=True, null=True, db_index=True)
    charging = models.IntegerField('Charging', default=0, blank=True, null=True, db_index=True)
    lts_update = models.DateTimeField('LTS Update', auto_now=False, blank=True, null=True, db_index=True)
    mark = models.CharField('Mark', max_length=20, blank=True, null=True, default='1.0.0', db_index=True)
    jarvis = models.CharField('Jarvis', max_length=20, blank=True, null=True, default='1.0.0', db_index=True)
    vision = models.CharField('Vision', max_length=20, blank=True, null=True, default='1.0.0', db_index=True)
    bus_img = models.ImageField(null=True, blank=True, default='bus.png', db_index=True)
    bus_ecu = models.CharField('Bus ECU', max_length=20, blank=True, null=True, choices=message_class_choices, db_index=True)
    soh = models.IntegerField('SOH', blank=True, null=True, db_index=True)
    bus_type = models.CharField('Type', max_length=20, blank=True, null=True, db_index=True)
    key_state = models.ImageField('Key State', null=True, blank=True, db_index=True)
    ecu_state = models.IntegerField('ECU State', blank=True, null=True, db_index=True)
 
    bus = models.Manager()

    def __str__(self):
        return f'{self.bus_name}'
    
    def delay_data(self):
        ahora = timezone.now()
        fecha_limite = ahora - timedelta(days=3)
        
        # Filtramos directamente en una sola consulta
        registros = Bus.bus.filter(
            lts_update__lt=fecha_limite
        )

        return registros


    class Meta:
        verbose_name = 'Bus'
        verbose_name_plural = 'Buses'
        ordering = ['bus_name']


class BitacoraCarga(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', blank=True, null=True)
    cycle_value = models.IntegerField('Clycle Value', null=True, blank=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)
    año = models.IntegerField()
    mes = models.IntegerField()

class Odometer(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', blank=True, null=True)
    odometer_value = models.IntegerField('Odometer Value', null=True, blank=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)

    odometer = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.odometer_value} - {self.bus}'

    class Meta:
        verbose_name = 'Odometer'
        verbose_name_plural = 'Odometers'
        ordering = ['TimeStamp']


class Soc(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', blank=True, null=True)
    soc_value = models.IntegerField('SOC Value', default=None, blank=True, null=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, blank=True, null=True)

    soc = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.soc_value} - {self.bus}'

    class Meta:
        verbose_name = 'SOC'
        verbose_name_plural = 'SOCs'
        ordering = ['TimeStamp']


class Battery24Volts(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', blank=True, null=True)
    battery_24_volts_value = models.FloatField('Battery 24 Volts Value', default=None, blank=True, null=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, blank=True, null=True)

    battery_24_volts = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.battery_24_volts_value} - {self.bus}'

    class Meta:
        verbose_name = 'Battery 24 Volts'
        verbose_name_plural = 'Batteries 24 Volts'
        ordering = ['TimeStamp']


class BatteryHealth(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', null=True, blank=True)
    battery_health_value = models.IntegerField('Battery Health', null=True, blank=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)

    battery_health = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.battery_health_value} - {self.bus}'

    class Meta:
        verbose_name = 'Battery Health'
        verbose_name_plural = 'Batteries Health'
        ordering = ['TimeStamp']


class FusiCode(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', blank=True, null=True)
    fusi_code = models.IntegerField()
    fusi_state = models.CharField('Fusi State', max_length=10, blank=True, null=True, default='open', choices=fusi_code_options)
    fusi_comment = models.TextField('Fusi Comment', blank=True, null=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)
    failure_odometer = models.IntegerField('Odometer', blank=True, null=True)

    fusi = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.fusi_code} - {self.fusi_state} - {self.fusi_comment} - ' \
               f'{self.failure_odometer} - {self.bus}'

    class Meta:
        verbose_name = 'Fusi Code'
        verbose_name_plural = 'Fusi Codes'
        ordering = ['TimeStamp']


class FusiMessage(models.Model):
    fusi_code = models.IntegerField()
    fusi_description = models.CharField('Fusi Description', max_length=500)
    message_class = models.CharField('Message Class', choices=message_class_choices, max_length=20, blank=True,
                                     null=True)

    fusi = models.Manager()

    def __str__(self):
        return f'{self.message_class}- {self.fusi_code} - {self.fusi_description}'

    class Meta:
        verbose_name = 'Fusi Message'
        verbose_name_plural = 'Fusi Messages'
        ordering = ['fusi_code']


class Isolation(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', blank=True, null=True)
    isolation_value = models.FloatField('Isolation', blank=True, null=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)

    isolation = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.isolation_value} - {self.bus}'

    class Meta:
        verbose_name = 'Isolation'
        verbose_name_plural = 'Isolations'
        ordering = ['TimeStamp']

class ChargeStatus(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', blank=True, null=True)
    charge_status_value = models.FloatField('Charge Status Value', blank=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)
    soc_level = models.IntegerField('SOC Level', blank=True, null=True)

    charge_status = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.charge_status_value} - {self.bus}'

    class Meta:
        verbose_name = 'Charge Status'
        verbose_name_plural = 'Charge Status'
        ordering = ['TimeStamp']

class HvilStatus(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', blank=True, null=True)
    hvil_status_value = models.IntegerField('HVIL Status Value', blank=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)

    hvil_status = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.hvil_status_value} - {self.bus}'

    class Meta:
        verbose_name = 'HVIL Status'
        verbose_name_plural = 'HVIL Status'
        ordering = ['TimeStamp']


class PackTemperature(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', null=True, blank=True)
    pack_temperature_value = models.FloatField('Pack Temperature', null=True, blank=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)

    pack_temperature = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.pack_temperature_value} - {self.bus}'

    class Meta:
        verbose_name = 'Pack Temperature'
        verbose_name_plural = 'Pack Temperatures'
        ordering = ['TimeStamp']


class MaxTemperaturePack(models.Model):
    TimeStamp = models.DateTimeField('TimeStamp', null=True, blank=True)
    max_temperature_pack_value = models.FloatField('Max Temperature Pack', null=True, blank=True)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, null=True, blank=True)

    max_temperature_pack = models.Manager()

    def __str__(self):
        return f'{self.TimeStamp} - {self.max_temperature_pack_value} - {self.bus}'

    class Meta:
        verbose_name = 'Max Temperature Pack'

bus_signals/forms.py
from django.forms import ModelForm
from .models import Bus, FusiMessage, FusiCode
from users.models import WorkOrder



class BusForm(ModelForm):
    class Meta:
        model = Bus
        fields = [
            'bus_name', 'sniffer', 'plate_number',
            'bus_series', 'client', 'vision', 'mark', 'jarvis', 'bus_img']


class FusiMessageForm(ModelForm):
    class Meta:
        model = FusiMessage
        fields = '__all__'


class FusiForm(ModelForm):
    class Meta:
        model = FusiCode
        fields = '__all__'

class WorkOrderForm(ModelForm):
    class Meta:
        model = WorkOrder
        fields = '__all__'

bus_signals/templates/bus_signals/bus_detail.html
{% extends "main.html" %} {% load static %} {% block content %}

<div class="container text-center" style="margin-left: 300px">
    <img src="{{ bus.bus_img.url }}" alt="image" style="width: 400px; height: 250px" />
    <h1>BUS {{ bus.bus_name}}</h1>
    <h5>Sniffer: {{ bus.sniffer}}</h5>
    <a href="{% url 'update_bus' bus.id %}"><button>Editar Bus</button></a>
    <a href="{% url 'delete_bus' bus.id %}"><button>Eliminar Bus</button></a>
    <a href="{% url 'work_order_form' %}"><button>Crear Parte</button></a>

    <span class="badge rounded-pill text-bg-secondary">Patente: {{ bus.plate_number}}</span>
    <h5>Kilometraje: {{ bus.lts_odometer }}</h5>
    <h5>Carga: {{ bus.lts_soc }}</h5>
    <h5>Serie: {{ bus.bus_series }}</h5>
    <h5>Cliente: {{ bus.client }}</h5>
    <h5>Version Mark: {{ bus.mark }}</h5>
    <h5>Version Jarvis: {{ bus.jarvis }}</h5>
    <h5>Version Vision: {{ bus.vision }}</h5>
    <h5>Baterias 24 Volts: {{ bus.lts_24_volt }}</h5>
    <h5>Aislacion: {{ bus.lts_isolation }}</h5>
    <h5>Actualizacion: {{ bus.lts_update }}</h5>

    <h2>Kilometrajes Diarios</h2>

    <table class="table">
        <tr>
            <th>Dia</th>
            <th>Enero</th>
            <th>Febrero</th>
            <th>Marzo</th>
            <th>Abril</th>
            <th>Mayo</th>
            <th>Junio</th>
            <th>Julio</th>
            <th>Agosto</th>
            <th>Septiembre</th>
            <th>Octubre</th>
            <th>Noviembre</th>
            <th>Diciembre</th>
        </tr>
        {% for i in results %}
        <tr>
            <td>{% if i.0 is None %} 0 {% else %}{{i.0}}{% endif %}</td>
            <td>{% if i.1 is None %} 0 {% else %}{{i.1}} Km{% endif %}</td>
            <td>{% if i.2 is None %} 0 {% else %}{{i.2}} Km{% endif %}</td>
            <td>{% if i.3 is None %} 0 {% else %}{{i.3}} Km{% endif %}</td>
            <td>{% if i.4 is None %} 0 {% else %}{{i.4}} Km{% endif %}</td>
            <td>{% if i.5 is None %} 0 {% else %}{{i.5}} Km{% endif %}</td>
            <td>{% if i.6 is None %} 0 {% else %}{{i.6}} Km{% endif %}</td>
            <td>{% if i.7 is None %} 0 {% else %}{{i.7}} Km{% endif %}</td>
            <td>{% if i.8 is None %} 0 {% else %}{{i.8}} Km{% endif %}</td>
            <td>{% if i.9 is None %} 0 {% else %}{{i.9}} Km{% endif %}</td>
            <td>{% if i.10 is None %} 0 {% else %}{{i.10}} Km{% endif %}</td>
            <td>{% if i.11 is None %} 0 {% else %}{{i.11}} Km{% endif %}</td>
            <td>{% if i.12 is None %} 0 {% else %}{{i.12}} Km{% endif %}</td>
        </tr>

        {% endfor %}
    </table>

    <h2>Kilometrajes Diarios</h2>

    <table class="table">
        <tr>
            <th>Bus</th>
            <th>Ene Min</th>
            <th>Ene Max</th>
            <th>Feb Min</th>
            <th>Feb Max</th>
            <th>Mar Min</th>
            <th>Mar Max</th>
            <th>Abr Min</th>
            <th>Abr Max</th>
            <th>May Min</th>
            <th>May Max</th>
            <th>Jun Min</th>
            <th>Jun Max</th>
            <th>Jul Min</th>
            <th>Jul Max</th>
            <th>Ago Min</th>
            <th>Ago Max</th>
            <th>Sep Min</th>
            <th>Sep Max</th>
            <th>Oct Min</th>
            <th>Oct Max</th>
            <th>Nov Min</th>
            <th>Nov Max</th>
            <th>Dic Min</th>
            <th>Dic Max</th>
        </tr>
        {% for i in monthly_result %}
        <tr>
            <td>{{ i.0 }}</td>
            <td>{% if i.1 is None %} 0 {% else %}{{i.1}} Km{% endif %}</td>
            <td>{% if i.2 is None %} 0 {% else %}{{i.2}} Km{% endif %}</td>
            <td>{% if i.3 is None %} 0 {% else %}{{i.3}} Km{% endif %}</td>
            <td>{% if i.4 is None %} 0 {% else %}{{i.4}} Km{% endif %}</td>
            <td>{% if i.5 is None %} 0 {% else %}{{i.5}} Km{% endif %}</td>
            <td>{% if i.6 is None %} 0 {% else %}{{i.6}} Km{% endif %}</td>
            <td>{% if i.7 is None %} 0 {% else %}{{i.7}} Km{% endif %}</td>
            <td>{% if i.8 is None %} 0 {% else %}{{i.8}} Km{% endif %}</td>
            <td>{% if i.9 is None %} 0 {% else %}{{i.9}} Km{% endif %}</td>
            <td>{% if i.10 is None %} 0 {% else %}{{i.10}} Km{% endif %}</td>
            <td>{% if i.11 is None %} 0 {% else %}{{i.11}} Km{% endif %}</td>
            <td>{% if i.12 is None %} 0 {% else %}{{i.12}} Km{% endif %}</td>
            <td>{% if i.13 is None %} 0 {% else %}{{i.13}} Km{% endif %}</td>
            <td>{% if i.14 is None %} 0 {% else %}{{i.14}} Km{% endif %}</td>
            <td>{% if i.15 is None %} 0 {% else %}{{i.15}} Km{% endif %}</td>
            <td>{% if i.16 is None %} 0 {% else %}{{i.16}} Km{% endif %}</td>
            <td>{% if i.17 is None %} 0 {% else %}{{i.17}} Km{% endif %}</td>
            <td>{% if i.18 is None %} 0 {% else %}{{i.18}} Km{% endif %}</td>
            <td>{% if i.19 is None %} 0 {% else %}{{i.19}} Km{% endif %}</td>
            <td>{% if i.20 is None %} 0 {% else %}{{i.20}} Km{% endif %}</td>
            <td>{% if i.21 is None %} 0 {% else %}{{i.21}} Km{% endif %}</td>
            <td>{% if i.22 is None %} 0 {% else %}{{i.22}} Km{% endif %}</td>
            <td>{% if i.23 is None %} 0 {% else %}{{i.23}} Km{% endif %}</td>
            <td>{% if i.24 is None %} 0 {% else %}{{i.24}} Km{% endif %}</td>
        </tr>
        {% endfor %}
    </table>

    <h2>Bitacora Bus</h2>

    {% for order in ot %}
    <p>
        {{order.title}} {{order.description}}

        <a href="{% url 'update_ot' order.id %}"><button>Editar Parte</button></a>
    </p>

    {% endfor %}
    <h2>Bitacora Codigos Fusi</h2>
    <table class="table">
        <tr>
            <th>Codigo Fusi</th>
            <th>Km</th>
            <th>Comentario</th>
            <th>Fecha</th>
            <th>Estado</th>
            <th></th>
        </tr>
        {% for i in fusi %}
        <tr>
            <td>{{i.fusi_code}}</td>
            <td>{{i.failure_odometer}}</td>
            <td>{{i.fusi_comment}}</td>
            <td>{{i.TimeStamp}}</td>
            <td>{{i.fusi_state}}</td>
            <td>
                <a href="{% url 'update-fusi-code' i.id  %}">
                    <button>Editar codigo fusi</button>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}

bus_signals/templates/bus_signals/bus_form.html
{% extends "main.html" %} {% load static %} {% block content %}
<br />
<br />
<br />
<br />

<h1 style="margin-left: 300px; margin-bottom: 40px">Ingresar nuevo bus a la flota</h1>

<div class="container" style="max-width: 700px">
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Nombre Bus</label>
            <input type="text" class="form-control" name="bus_name" value="{{bus.bus_name}}" />
        </div>
        <div class="mb-3">
            <label class="form-label">Sniffer</label>
            <input type="text" class="form-control" name="sniffer" value="{{bus.sniffer}}" />
        </div>
        <div class="mb-3">
            <label class="form-label">Patente</label>
            <input
                type="text"
                class="form-control"
                name="plate_number"
                value="{{bus.plate_number}}"
            />
        </div>
        <div class="mb-3">
            <label class="form-label">Serie Bus</label>
            <select
                class="form-select"
                style="margin-bottom: 20px"
                name="bus_series"
                aria-invalid="true"
                id="id_bus_series"
            >
                <option selected>{{bus.bus_series}}</option>
                <option value="Queltehue">Queltehue</option>
                <option value="Tricahue">Tricahue</option>
                <option value="Retrofit">Retrofit</option>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label">Cliente</label>
            <input type="text" class="form-control" name="client" value="{{bus.client}}" />
        </div>
        <div class="mb-3">
            <label class="form-label">Vision</label>
            <input type="text" class="form-control" name="vision" value="{{bus.vision}}" />
        </div>
        <div class="mb-3">
            <label class="form-label">Mark</label>
            <input type="text" class="form-control" name="mark" value="{{bus.mark}}" />
        </div>
        <div class="mb-3">
            <label class="form-label">Jarvis</label>
            <input type="text" class="form-control" name="jarvis" value="{{bus.jarvis}}" />
        </div>
        <div class="mb-3">
            <label class="form-label">Imagen Bus</label>
            {{form.bus_img}}
        </div>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>

{% endblock %}

bus_signals/templates/bus_signals/bus_list.html
{% extends "main.html" %} {% block content %}
<br />
<br />
<br />
<br />
<div style="margin-left: 300px">
    <h1>Flota E-Buses</h1>

    <a href="{% url 'create_bus' %}"><button>Crear Bus</button> </a>
    <!--buscador de buses-->
    <form action="{% url 'bus_list' %}" method="get">
        <div>
            <label>Buscar Bus </label>
            <input
                type="text"
                name="search_query"
                value="{{ search_query }}"
                placeholder="Ingrese : Bus, Serie Bus, ECU Bus, Cliente"
            />
        </div>

        <input type="submit" value="Buscar" />
    </form>
    <!--lista buses-->
    <div class="container text-center">
        <div class="row">
            {% for bus in bus %}
            <div class="col-sm-4">
                <div class="card mb-4" style="max-width: 540px">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img
                                src="{{ bus.bus_img.url }}"
                                class="img-fluid rounded-start"
                                alt="bus image"
                            />
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <a href="{% url 'bus_detail' bus.id %}">
                                    <h5 class="card-title">{{bus.bus_name}}</h5>
                                    <p class="card-text">
                                        {{bus.plate_number}} <br />
                                        {{bus.lts_soc}}% <br />
                                        {{bus.lts_odometer}} Kms.
                                    </p>
                                    <p class="card-text">
                                        <small class="text-body-secondary"
                                            >{{bus.lts_update}}</small
                                        >
                                    </p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if bus.has_other_pages %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if bus.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{bus.previous_page_number}}">Anterior</a>
                </li>
                {% endif %} {% for page in paginator.page_range %} {% if page == bus.number %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{page}}">{{page}}</a>
                </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                {% endif %} {% endfor %} {% if bus.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{bus.next_page_number}}">Siguiente</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>

    {% endblock content %}
</div>

bus_signals/templates/bus_signals/dic_fusi.html
{% extends "main.html" %} {% load static %} {% block title %} Diccionario fusi {% endblock title %}
{% block content %}
<div class="container text-center" style="margin-left: 300px">
    <h1>Diccionario fusi</h1>
    <a href="{% url 'create_fusi' %}"><button>Agregar Fusi</button></a>
    <br />
    <form id="searchForm" class="form" action="{% url 'dic_fusi' %}" method="get">
        <div class="form__field">
            <label for="formInput#search">Buscar Codigo Fusi </label>
            <input
                class="input input--text"
                id="formInput#search"
                type="text"
                name="search_query"
                value="{{ search_query }}"
                placeholder="Ingrese : Codigo, Componente, Descripcion, Tipo ECU"
            />
        </div>

        <input class="btn btn--sub btn--lg" type="submit" value="Buscar" />
    </form>

    <table>
        <tr>
            <th>Codigo</th>
            <th>Descripcion</th>
            <th>Clase</th>
            <th></th>
        </tr>
        {% for i in fusi %}
        <tr>
            <td>{{ i.fusi_code }}</td>
            <td>{{ i.fusi_description }}</td>
            <td>{{ i.message_class }}</td>
            <td>
                {% if user.username == 'usuario_link' %}
                <button type="button" class="btn btn-outline-success" disabled>Editar</button>
                {% else %}
                <a href="{% url 'update_fusi' i.id %}">
                    <button type="button" class="btn btn-outline-success" disabled>
                        Editar
                    </button></a
                >
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
    <!--paginador-->
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if fusi.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{fusi.previous_page_number}}">Anterior</a>
            </li>
            {% endif %} {% for page in paginator.page_range %} {% if page == fusi.number %}
            <li class="page-item active">
                <a class="page-link" href="?page={{page}}">{{page}}</a>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
            {% endif %} {% endfor %} {% if fusi.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{fusi.next_page_number}}">Siguiente</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <!--fin paginador-->
</div>

{% endblock content %}