Alicanto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bus_signals.urls")),
    path('api/', include("link_apis.urls")),
    path('', include("users.urls")),
    path('', include("reports.urls")),
    path('', include('programacion_bus.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profiles', views.profile, name='profile'),
    path('work_order/', views.create_work_order, name='work_order_form'),
    path('update_ot/<str:pk>/', views.update_ot, name='update_ot'),
    

]

users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from bus_signals.models import Bus


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    company = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    job_title = models.CharField(max_length=100, blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')

    def __str__(self):
        return str(self.user.username)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'
        ordering = ['created']


class WorkOrder(models.Model):
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} - {self.bus} - {self.created}'

    class Meta:
        verbose_name = 'Work Order'
        verbose_name_plural = 'Work Orders'
        ordering = ['created']

users/views.py
from django.shortcuts import render
from bus_signals.models import Bus, ChargeStatus, Odometer
from bus_signals.query_utils import obtener_ultimo_valor_energia
from django.db.models import F, Max, Window
from django.db.models.functions import ExtractMonth, ExtractDay
# Create your views here.
from django.shortcuts import render, redirect
from bus_signals.forms import WorkOrderForm
from .models import WorkOrder, Profile
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import pytz
from django.utils import timezone
from collections import defaultdict
from datetime import datetime, timedelta
from django.db.models import F, Case, When, IntegerField, Window
from django.db.models.functions import RowNumber
from itertools import groupby
no_update_list = [ '27','34', '60', '24', '87', '116', '21', '61', '82', '83', '81', '87', '137', '132', '134', '133', '130', '129', '128', '131', '136', '135' ]
# Create your views here.
@login_required(login_url='login')
def profile(request):
    workers = Profile.objects.all()
    context = {'workers': workers}
    return render(request, 'users/profile.html', context)

@login_required(login_url='login')
def work_order(request):
    return render(request, 'users/work_order_form.html')

@login_required(login_url='login')
def create_work_order(request):
    form = WorkOrderForm()
    if request.method == 'POST':
        form = WorkOrderForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('bus_list')
    context = {'form': form}
    return render(request, 'users/work_order_form.html', context)

@login_required(login_url='login')
def update_ot(request, pk):
    ot = WorkOrder.objects.get(id=pk)
    form = WorkOrderForm(instance=ot)
    if request.method == 'POST':
        form = WorkOrderForm(request.POST, request.FILES, instance=ot)
        if form.is_valid():
            form.save()
            return redirect('bus_list')
    context = {'form': form}
    return render(request, 'users/work_order_form.html', context)

def format_date(date):
    return date.strftime('%d/%m/%Y')  # Formato: día/mes/año

users/templates/users/profile.html
{% extends 'main.html' %} {% load static %} {% block header %}Staff {% endblock header %} {% block content %}
<link rel="stylesheet" href="{% static 'styles/profiles.css' %}" />
<div class="container-fluid">
    <!--divisor de codigo-->
    <div class="row">
        {% for i in workers %}
        <div class="col-4">
            <div style="margin-top: 30px" class="card">
                <div class="row g-0">
                    <div class="col-3">
                        <img
                            style="object-fit: cover"
                            src="{{i.profile_image.url}}"
                            class="img-fluid rounded-start serie"
                            alt="profileimage"
                        />
                    </div>
                    <div class="col-9">
                        <div class="card-body">
                            <h5 class="card-title">{{i.name}}</h5>
                            <br />
                            <div class="card-text">
                                <div class="content-container">
                                    <div class="name">Area:</div>
                                    <div class="name">Correo</div>
                                    <div class="name">Telefono:</div>
                                </div>
                                <div class="content-container">
                                    <div class="item">{{i.short_intro}}</div>
                                    <div class="item">{{i.email}}</div>
                                    <div class="item">{{i.phone}}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

users/templates/users/work_order_form.html
{% extends "main.html" %} {% load static %} {% block content %}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="container text-center" style="margin-left: 300px">
    <h1>Crear Parte</h1>
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
                <form class="form" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <!-- Input:Text -->
                    {% for field in form %}
                    <div class="form__field">
                        <label for="formInput#text">{{field.label}}: </label>
                        {{field}}
                    </div>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
</div>

<div>
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
</div>
<div class="container" style="max-width: 700px">
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Nombre Bus</label>
            <select
                class="form-select"
                style="margin-bottom: 20px"
                name="bus_series"
                aria-invalid="true"
                id="id_bus"
            >
                <option selected>Seleccione un bus</option>
                {% for i in form.bus %}
                <option value="{{i}}"></option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label">Titulo</label>
            <input type="text" class="form-control" />
        </div>
        <div class="mb-3">
            <label class="form-label">Descripcion</label>

            <textarea
                class="form-control"
                style="margin-bottom: 20px"
                name="description"
                id="id_description"
            ></textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">Reportante</label>
            <input type="text" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Crear Registro</button>
    </form>
</div>

{% endblock %}